Feature/messaging redis
extreal-dev/Extreal.Integration.Messaging.Socket.IO pull request #1
Opened 2023-12-18 02:25 UTC by mahaweilu

# 何の変更を加えましたか？

# 何を確認しましたか?

## 実装

- [ ] Frameworkの誤った使い方にすぐに気づけるように、無効な引数や無効なメソッド呼び出しに対するチェックが入っていることを確認しました
- [ ] Framework実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [ ] 静的解析で問題が見つからないことを確認しました
- [ ] フレームワーク利用者が使うAPI（主にprivate以外）に C# ドキュメントを記述しました

## テスト

- [ ] 全ての自動テストが成功することを確認しました
- [ ] テストカバレッジが100%になることを確認しました
- [ ] サンプルがあるものはサンプルが動作することを確認しました

## 変更影響

- [ ] GuideのReleaseページに変更内容が追加されることを確認しました
- [ ] GuideのModuleページ（機能ページ）に変更が反映されることを確認しました
- [ ] GuideのLearningページに変更が反映されることを確認しました
- [ ] Sample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2023-12-27 07:15 UTC, mahaweilu commented on Runtime/Extreal.Integration.Messaging.Redis.asmdef
> +        "Extreal.SampleApp.Holiday.Analyzer",
既存ライブラリのアセンブリと同じように、Analyzerが不要です。

https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/blob/main/Runtime/Extreal.Integration.Multiplay.NGO.asmdef

2023-12-27 07:15 UTC, mahaweilu commented on Runtime/RedisMessagingClient.cs
> +    /// Class that implement IMessagingTransport using Redis.
IMessagingTransport　-> MessagingClient, implement -> implements

2023-12-27 07:15 UTC, mahaweilu commented on Runtime/RedisMessagingClientProvider.cs
> +    /// Class that provides RedisMessagingTransport.
RedisMessagingTransport -> RedisMessagingClient

2023-12-27 07:15 UTC, mahaweilu commented on Runtime/RedisMessagingClientProvider.cs
> +        /// Provides RedisMessagingTransport.
RedisMessagingTransport -> RedisMessagingClient, このファイルのdocsについても同じようなところがないかを確認・修正お願いします。

2023-12-27 07:15 UTC, mahaweilu commented on Runtime/RedisMessagingConfig.cs
> +        /// <param name="url">URL of the redis server.</param>
redis server　-> messaging server, このファイル内で他にredis serverの表現あるかどうかを確認・修正お願いします。

2023-12-27 07:15 UTC, mahaweilu commented on package.json
> +    "jp.co.tis.extreal.integration.messaging.common": "1.0.0-Next.1"
Next -> next

2023-12-27 08:11 UTC, mahaweilu commented on Samples~/MVS/GroupSelectionScreen/GroupSelectionScreen.unity
> +    TypeName: Extreal.Integration.Messaging.Redis.MVS.Controls.ClientControl.ClientControlScope
ディレクトリ構成が変わってこちらの修正がされていないです。シーンでparent scopeを設定し直すように修正お願いします。タイトルシーンについても同様です。
Extreal.Integration.Messaging.Redis.MVS.ClientControl.ClientControlScope

2023-12-28 04:42 UTC, sus-yoshikane-t requested changes

2023-12-28 04:42 UTC, sus-yoshikane-t commented on Samples~/MVS/SpaceControl/SpaceControl.unity
Scope等のクラスとしてChat.WebRTCのものが設定されてしまっています。

2023-12-28 04:42 UTC, sus-yoshikane-t commented on Samples~/MVS/TextChatControl/TextChatControl.unity
Scope等のクラスとしてChat.WebRTCのものが設定されてしまっています。

2023-12-28 04:42 UTC, sus-yoshikane-t commented on Runtime/NativeRedisMessagingClient.cs
> +        private readonly CancellationTokenSource cancellationForSocketInProgress = new CancellationTokenSource();
CC0033の静的解析が出ています。

2023-12-28 04:42 UTC, sus-yoshikane-t commented on Runtime/WebGLRedisMessagingClient.cs
> +        private readonly CompositeDisposable disposables = new CompositeDisposable();
CC0033の静的解析が出ています。

2023-12-28 04:42 UTC, sus-yoshikane-t commented on WebScripts~/src/RedisMessagingClient.ts
> +  private getSocket = (handle: () => void) => {
connectErrorHandle等の方が分かりやすいと思いました。
```suggestion
  private getSocket = (connectErrorHandle: () => void) => {
```

2023-12-28 04:42 UTC, sus-yoshikane-t commented on Runtime/WebGLRedisMessagingClient.cs
> +            }
disposablesはこの外でDisposeし、この中ではStaticDisposablesがDisposeされるべきです。
```suggestion
            disposables.Dispose();

            instanceNum--;
            if (instanceNum == 0)
            {
                StaticDisposables.Dispose()
            }
```

2023-12-28 04:42 UTC, sus-yoshikane-t commented on Samples~/MVS/TextChatControl/TextChatMessage.prefab
TextChatMessageViewクラスとしてChat.WebRTCのものが設定されてしまっています。

2023-12-28 04:42 UTC, sus-yoshikane-t commented on Samples~/MVS/TextChatControl/TextChatMessageView.cs
> +            rectTransform.sizeDelta = sizeDelta;
rectTransform.sizeDeltaに設定していないのでmessageText.preferredHeightが更新されていません。(ここで入ったものではないとは思いますが。)
文字列更新時のmessageText.preferredHeightの高さになり、長い文字列だと画面外に出ることがあります。
```suggestion
            rectTransform.sizeDelta = new Vector2(messageText.preferredWidth, messageText.preferredHeight);
            rectTransform.sizeDelta = new Vector2(sizeDelta.x, messageText.preferredHeight);
```

2024-01-09 00:58 UTC, mahaweilu commented on Runtime/RedisMessagingClient.cs
> +    /// Class that implement IMessagingTransport using Redis.
fixed [2648251](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/2648251c920b4c951fd56ea0c91137afc99068a3)

2024-01-09 00:58 UTC, mahaweilu commented on Runtime/RedisMessagingClientProvider.cs
> +    /// Class that provides RedisMessagingTransport.
fixed [2648251](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/2648251c920b4c951fd56ea0c91137afc99068a3)

2024-01-09 00:59 UTC, mahaweilu commented on Runtime/RedisMessagingClientProvider.cs
> +        /// Provides RedisMessagingTransport.
fixed [2648251](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/2648251c920b4c951fd56ea0c91137afc99068a3)

2024-01-09 01:02 UTC, mahaweilu commented on Runtime/RedisMessagingConfig.cs
> +        /// <param name="url">URL of the redis server.</param>
fixed [ee3aad1](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/ee3aad1faa9cda8f2e4dcb1f0805cda02ce009b5)

2024-01-09 01:13 UTC, mahaweilu commented on package.json
> +    "jp.co.tis.extreal.integration.messaging.common": "1.0.0-Next.1"
fixed [b59cc74](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/b59cc74f766ecf15d510cce4f8d8e6a9a826b76a)

2024-01-09 01:22 UTC, mahaweilu commented on Samples~/MVS/GroupSelectionScreen/GroupSelectionScreen.unity
> +    TypeName: Extreal.Integration.Messaging.Redis.MVS.Controls.ClientControl.ClientControlScope
>タイトルシーンについても同様です。

タイトルシーンについて問題がありませんでした。
関連するところを以下で修正しました。

fixed [4c8c304](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/4c8c3048ca3ea294724fa108846a1ae0e3e832e8)

2024-01-09 01:23 UTC, mahaweilu commented on Samples~/MVS/SpaceControl/SpaceControl.unity
以下で対応しました。
[4c8c304](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/4c8c3048ca3ea294724fa108846a1ae0e3e832e8)

2024-01-09 01:23 UTC, mahaweilu commented on Samples~/MVS/TextChatControl/TextChatControl.unity
以下で対応しました。
[4c8c304](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/4c8c3048ca3ea294724fa108846a1ae0e3e832e8)

2024-01-09 01:27 UTC, mahaweilu commented on Runtime/NativeRedisMessagingClient.cs
> +        private readonly CancellationTokenSource cancellationForSocketInProgress = new CancellationTokenSource();
修正しました。
[424d328](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/424d328908091dccdc197dd9a34a50e64f68ec7e)

2024-01-09 01:27 UTC, mahaweilu commented on Runtime/WebGLRedisMessagingClient.cs
> +        private readonly CompositeDisposable disposables = new CompositeDisposable();
修正しました。
[424d328](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/424d328908091dccdc197dd9a34a50e64f68ec7e)

2024-01-09 02:54 UTC, mahaweilu commented on Samples~/MVS/TextChatControl/TextChatMessage.prefab
chat.webrtcのmvsと同時に導入した場合に、発生する現象だと思います。個別でそれぞれ導入した場合に問題なかったので対応不要とします。

2024-01-09 04:21 UTC, mahaweilu commented on Runtime/Extreal.Integration.Messaging.Redis.asmdef
> +        "Extreal.SampleApp.Holiday.Analyzer",
fixed [ae12884](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/ae128842dce513f5635087b7fef7a656e649068c)

2024-01-09 04:23 UTC, mahaweilu commented on Runtime/WebGLRedisMessagingClient.cs
> +            }
指摘通りに対応しました。
[e0ce708](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/e0ce70874c749e60190ccec1ee6ef48e63fa4fa1)

2024-01-09 04:23 UTC, mahaweilu commented on Samples~/MVS/TextChatControl/TextChatMessageView.cs
> +            rectTransform.sizeDelta = sizeDelta;
指摘通り対応しました。
[6c9ea64](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/6c9ea642529b85eedbf987e10feb42f283cbda22)

2024-01-09 04:24 UTC, mahaweilu commented on WebScripts~/src/RedisMessagingClient.ts
> +  private getSocket = (handle: () => void) => {
指摘通り対応しました。
[e12bc3e](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/e12bc3ed4afbf80f95baf76756bf1d097373079d)

2024-01-09 06:48 UTC, sus-yoshikane-t commented on Runtime/NativeRedisMessagingClient.cs
> +        private readonly CancellationTokenSource cancellationForSocketInProgress = new CancellationTokenSource();
確認しました。

2024-01-09 06:49 UTC, sus-yoshikane-t commented on Runtime/WebGLRedisMessagingClient.cs
> +        private readonly CompositeDisposable disposables = new CompositeDisposable();
確認しました。

2024-01-09 08:02 UTC, sus-yoshikane-t commented on WebScripts~/src/RedisMessagingClient.ts
> +  private getSocket = (handle: () => void) => {
確認しました。

2024-01-09 08:03 UTC, sus-yoshikane-t commented on Runtime/WebGLRedisMessagingClient.cs
> +            }
確認しました。

2024-01-09 08:04 UTC, sus-yoshikane-t commented on Samples~/MVS/TextChatControl/TextChatMessageView.cs
> +            rectTransform.sizeDelta = sizeDelta;
確認しました。(2行目の1つ目の引数が誤っていたのも直していただきありがとうございます。)

2024-01-09 08:06 UTC, sus-yoshikane-t commented on Samples~/MVS/SpaceControl/SpaceControl.unity
単体で入れて問題ないことを確認しました。([参照](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1#discussion_r1445575475))

2024-01-09 08:06 UTC, sus-yoshikane-t commented on Samples~/MVS/TextChatControl/TextChatControl.unity
単体で入れて問題ないことを確認しました。([参照](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1#discussion_r1445575475))

2024-01-09 08:06 UTC, sus-yoshikane-t commented on Samples~/MVS/TextChatControl/TextChatMessage.prefab
単体で入れて問題ないことを確認しました。

2024-01-09 08:48 UTC, mahaweilu commented on Runtime/Extreal.Integration.Messaging.Redis.asmdef
> +        "Extreal.SampleApp.Holiday.Analyzer",
CIで検知できるようになっていて、マージ前に削除するそうなので、"Extreal.Framework.Analyzer"を使うように戻しました。最終的に削除します。
[93f02e4](https://github.com/extreal-dev/Extreal.Integration.Messaging/pull/1/commits/93f02e41becbd1567368bec2fe2d52c107a79a38)

2024-01-16 09:48 UTC, kiyohome requested changes

2024-01-16 09:48 UTC, kiyohome commented on MessagingServer~/Dockerfile
> +# 参考：https://maku.blog/p/ehxgwt4/
FW利用プロジェクトが参考にするので、参考URLやコメント消しませんか。

2024-01-16 09:48 UTC, kiyohome commented on MessagingServer~/compose.yaml
> +    sigredis:
こっちはredisですよね？

2024-01-16 09:48 UTC, kiyohome commented on MessagingServer~/compose.yaml
> +    redispubsub:
こっちはsignalingですよね？違うのかな？

2024-01-16 09:48 UTC, kiyohome commented on MessagingServer~/compose.yaml
> +        # ports:
このコメントは必要ですか？

2024-01-16 09:48 UTC, kiyohome commented on MessagingServer~/package.json
> +  "name": "comet-gameserver-wssrv",
nameを見直して欲しいです

2024-01-16 09:48 UTC, kiyohome commented on MessagingServer~/package.json
> +  "name": "comet-gameserver-wssrv",
他もすべて一度見直しをお願いします。

2024-01-16 09:48 UTC, kiyohome commented on MessagingServer~/package.json
> +  "name": "comet-gameserver-wssrv",
P2P.WebRTCと比べて依存が増えていて全て必要なのか気になります。
あと依存先のバージョンも。できるだけ最小限にして欲しいです。
そうしないと依存モジュールでセキュリティパッチが出るたびにメンテが必要になります。

2024-01-16 09:48 UTC, kiyohome commented on MessagingServer~/src/index.ts
> +app.get("/", (req, res) => {
これ使ってますか？

2024-01-16 09:48 UTC, kiyohome commented on MessagingServer~/src/index.ts
> +app.get("/metrics", async (req, res) => {
こちらも使ってますか？

2024-01-16 09:48 UTC, kiyohome commented on MessagingServer~/src/index.ts
> +app.get("/metrics", async (req, res) => {
必要なものだけの最小限の実装になってますか？

2024-01-16 09:48 UTC, kiyohome commented on MessagingServer~/src/index.ts
> +import express from "express";
P2P.WebRTCに合わせないですか？
Deno使うとか、静的解析周りとか。。。

2024-01-16 09:48 UTC, kiyohome commented on MessagingServer~/src/index.ts
> +      console.log(JSON.stringify(Object.fromEntries(groupList)));
ログが常に出ないでしょうか？

2024-01-16 09:48 UTC, kiyohome commented on MessagingServer~/src/index.ts
> +      const maxCapacityStr = await redisClient.get(
redisClientへのアクセスを局所化したクラスを作って、そこでredisとsignalingの間の差異を吸収する処理を入れた方がよいです。redisの具体的なキーなどをsignaling側に見せないようにしたいです。

2024-01-16 09:48 UTC, kiyohome commented on MessagingServer~/src/index.ts
> +      const groupList = await getGroupList();
Redistに入れてるグループとSocket.IOのルームはどのような関係でしょうか？
2つ使うのであれば分かるように実装しないと複雑ですね。

2024-01-16 09:48 UTC, kiyohome commented on Runtime/WebGLRedisMessagingClient.cs
> +        private static int instanceNum;
ソース追いかけられてないのですが、instanceIdとinstanceNumは何に使ってますか？

2024-01-17 01:05 UTC, mahaweilu commented on MessagingServer~/compose.yaml
> +    sigredis:
composeファイルのリファクタリングについて以下で修正しました。
[a1151ac](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/a1151ac48c8311bff9edcca94b7721a5528136ee)

2024-01-17 01:09 UTC, mahaweilu commented on MessagingServer~/compose.yaml
> +    redispubsub:
messagingに修正しました（P2P.WebRTCのほうにsignalingを使っているため、コンテナを区別する意図）

[a1151ac](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/a1151ac48c8311bff9edcca94b7721a5528136ee)

2024-01-17 01:09 UTC, mahaweilu commented on MessagingServer~/compose.yaml
> +        # ports:
削除しました。

[a1151ac](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/a1151ac48c8311bff9edcca94b7721a5528136ee)

2024-01-17 05:38 UTC, mahaweilu commented on MessagingServer~/src/index.ts
> +      const maxCapacityStr = await redisClient.get(
memo:
・責務の話、redisClientみたいなクラスを作成してredis関係を吸収し、signaling責務部分でredisClientを利用して呼び出すように
・signaling: clientとやり取りの部分
・グループ管理

2024-01-17 05:53 UTC, mahaweilu commented on MessagingServer~/src/index.ts
> +      const groupList = await getGroupList();
memo: 
・p2pの時と違い、人がいなくてもgroupを作成・削除がしたい
　・groupを作るとgroupに入るを分ける要件がある
　　・これでgroupは個別で管理した方が良いかと考え
       ・同時に要件が増え：createGroupでgroupList.add, deleteGroupでgroupList.remove

2024-01-17 07:22 UTC, mahaweilu commented on Runtime/WebGLRedisMessagingClient.cs
> +        private static int instanceNum;
instanceIdは以下の理由で必要です。
・C#側で複数（chat + multiplay）存在する可能性がある
・JS側で呼び出すcallback（WebGLHelper.AddCallback）がstaticで1つしかなく、C#のchatかmultiplayどのインスタンスがが呼び出しているかを識別する必要がある。識別子で呼び出すようにしないとchatでcallbackを呼んでもmultiplay側も呼び出されてしまう

instanceNumは以下の理由で必要です。
・C#側のインスタンスで作成したイベント（onGroupListResponseReceivedなど）のリソースを解放する必要がある
・複数（chat + multiplay）のインスタンスが全部なくなってからリソースを解放する

2024-01-17 13:58 UTC, mahaweilu commented on MessagingServer~/src/index.ts
> +app.get("/", (req, res) => {
削除しました。
[4235004](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/4235004e9cd68e3648fbd7b158777bdfb388453a)

2024-01-17 13:58 UTC, mahaweilu commented on MessagingServer~/src/index.ts
> +app.get("/metrics", async (req, res) => {
不要部分を確認し削除しました。
[4235004](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/4235004e9cd68e3648fbd7b158777bdfb388453a)

2024-01-17 13:59 UTC, mahaweilu commented on MessagingServer~/src/index.ts
> +      console.log(JSON.stringify(Object.fromEntries(groupList)));
isLoggingがonの時だけ出力するように修正しました。
[4235004](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/4235004e9cd68e3648fbd7b158777bdfb388453a)

2024-01-17 14:01 UTC, mahaweilu commented on MessagingServer~/src/index.ts
> +      const maxCapacityStr = await redisClient.get(
RedisClientというクラスを作成し、signaling部分でRedisClientのメソッドを呼び出すように修正しました。
[7d1760a](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/7d1760af5871d8a012bbeca5d72ea9ffbd3b2f34)

2024-01-17 14:13 UTC, mahaweilu commented on MessagingServer~/src/index.ts
> +      const groupList = await getGroupList();
>Redistに入れてるグループとSocket.IOのルームはどのような関係でしょうか？

同じ物なため、groupという概念で統一し命名修正しました。

>redisClientへのアクセスを局所化したクラスを作って、そこでredisとsignalingの間の差異を吸収する処理を入れた方がよいです。redisの具体的なキーなどをsignaling側に見せないようにしたいです。

↑こちらの対応で、signalingで使う部分は全部groupという概念で統一し命名修正しました。

[7d1760a](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/7d1760af5871d8a012bbeca5d72ea9ffbd3b2f34)
[df84c87](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/df84c87718e4ef7dd0ecd8f2899c1da60c0369c9)

2024-01-18 01:50 UTC, sus-yoshikane-t approved these changes

2024-01-18 07:03 UTC, mahaweilu commented on MessagingServer~/src/index.ts
> +import express from "express";
Denoを使うように対応します。

2024-01-18 07:05 UTC, mahaweilu commented on MessagingServer~/package.json
> +  "name": "comet-gameserver-wssrv",
p2p.webrtcと同じようにdenoを使えば、最小限にできるため、denoを使うように対応します。

2024-01-18 07:33 UTC, mahaweilu commented on MessagingServer~/src/index.ts
> +import express from "express";
対応しました。
[8573dc1](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/8573dc165a879a9f9388fd9884b98aa3d2b64764)

2024-01-18 07:34 UTC, mahaweilu commented on MessagingServer~/package.json
> +  "name": "comet-gameserver-wssrv",
対応しました。[8573dc1](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/8573dc165a879a9f9388fd9884b98aa3d2b64764)

2024-01-18 07:34 UTC, mahaweilu commented on MessagingServer~/Dockerfile
> +# 参考：https://maku.blog/p/ehxgwt4/
denoを使うように対応したため、こちらのファイルが要らなくなっています。
[8573dc1](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/8573dc165a879a9f9388fd9884b98aa3d2b64764)

2024-01-18 08:30 UTC, mahaweilu commented on MessagingServer~/src/index.ts
> +      const groupList = await getGroupList();
~方針：createGroupとdeleteGroupを削除する
・messagingライブラリのcreateGroup,deleteGroupを削除
・サーバ側もcreateGroup,deleteGroup
・GroupManagerを作りグループ管理を行う
　・createGroupとdeleteGroupは~

2024-01-18 10:04 UTC, mahaweilu commented on Runtime/WebGLRedisMessagingClient.cs
> +        private static int instanceNum;
方針：
instanceNumを使わないようにする

2024-01-23 09:34 UTC, mahaweilu commented on Runtime/WebGLRedisMessagingClient.cs
> +        private static int instanceNum;
以下で対応しました。
[0135eb6](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/0135eb6c05c0fe6ab1f35e08208e7fe75576ab16)

テストケースも追加しています。
[51b896f](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/51b896f338443496859639a739e92e97b5905cee)

2024-01-23 10:25 UTC, mahaweilu commented on MessagingServer~/src/index.ts
> +      const groupList = await getGroupList();
MessagingClientのcreateGroupとdeleteGroupを削除したため、Redis.Messagigモジュールで関連するC#, JS部分を修正して対応しました。
[0135eb6](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/0135eb6c05c0fe6ab1f35e08208e7fe75576ab16)

2024-01-23 10:27 UTC, mahaweilu commented on MessagingServer~/src/index.ts
> +      const maxCapacityStr = await redisClient.get(
denoへの変更にあわせて修正しました。
[8573dc1](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/8573dc165a879a9f9388fd9884b98aa3d2b64764)

[782b55c](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/782b55c3a1856ab1a37c127c5de3af7a41701ba1)

2024-01-23 10:35 UTC, mahaweilu commented on MessagingServer~/src/index.ts
> +app.get("/metrics", async (req, res) => {
必要なものだけの最小限の実装になってますか？
denoへの変更でindex.tsが変わりましたので

2024-01-26 10:46 UTC, kiyohome requested changes

2024-01-26 10:46 UTC, kiyohome commented on MessagingServer~/compose.yaml
> +    messaging-redis:
messaging-redisはredisだけだとダメでしょうか？
単体のcomposeファイル内でユニークに分かるシンプルな名前でいいと思いました。
何か理由ありますか？

2024-01-26 10:46 UTC, kiyohome commented on MessagingServer~/compose.yaml
> +        image: redis:7.0.10-alpine
redisは7.2が最新のstableみたいですがダメでしょうか？

2024-01-26 10:46 UTC, kiyohome commented on MessagingServer~/compose.yaml
> +        tty: true
下記は必要ですか？

- tty
- init
- expose

2024-01-26 10:46 UTC, kiyohome commented on MessagingServer~/index.ts
> +    const maxCapacityStr = await this.client.get(`MaxCapacity#${groupName}`);
MaxCapacityをどうしてRedisに保存してるのでしょうか？

2024-01-26 10:46 UTC, kiyohome commented on MessagingServer~/index.ts
> +    await this.client.set(clientId, socketId);
こちらもRedisに保存している理由はありますか？

2024-01-26 10:46 UTC, kiyohome commented on MessagingServer~/index.ts
> +const log = (...logMessages: (string | object)[]) => {
ログの文字列を受け取ると、ログの出力有無に関わらず、呼び出し元で毎回文字列が生成されるので、性能観点でよくないです。

2024-01-26 10:46 UTC, kiyohome commented on MessagingServer~/index.ts
> +const getGroupsInfo = (): { groupList: Map<string, string>, groupMembers: Map<string, string[]> } => {
"list groups"でこの関数を呼んでますがオーバースペックではないでしょうか？
groupMembersを使ってないように思います。

2024-01-26 10:46 UTC, kiyohome commented on MessagingServer~/index.ts
> +  const groupsMap = io.of("/").adapter.rooms;
xxxMapやxxxListなど、実装手段は変数名などの名前に使用しない方がいいと思います。
実装手段が変わったら全ての名前を変えないといけないので。
単純に複数系にしておけばいいと思います。

2024-01-26 10:46 UTC, kiyohome commented on MessagingServer~/index.ts
> +      clientId: string,
clientIdを指定せずにsocketIdをクライアントIDとしたらダメでしょうか？
全体的にもっとシンプルになるような気がしました。

2024-01-26 10:46 UTC, kiyohome commented on MessagingServer~/index.ts
> +      maxCapacity: number,
maxCapacityをここで渡すのは違和感があります。
やりたいことは何でしょうか？

2024-01-26 10:46 UTC, kiyohome commented on MessagingServer~/index.ts
> +  const handleDisconnect = async () => {
こちらだけどうして関数を定義して、on関数で渡してるのでしょうか？

2024-01-26 10:46 UTC, kiyohome commented on MessagingServer~/index.ts
> +  let myGroupName = "";
ここに状態を持たなくても、socket.idでクライアントを識別できるので、参加できるroomが1つなのであれば、roomsから参加しているルーム名を取れませんかね？

2024-01-26 10:46 UTC, kiyohome commented on Runtime/NativeRedisMessagingClient.cs
> +                localClientId, connectionConfig.GroupName, connectionConfig.MaxCapacity
毎回MaxCapacityを指定するのはやっぱり不自然に感じます。

2024-01-26 10:46 UTC, kiyohome commented on Runtime/NativeRedisMessagingClient.cs
> +        protected override async UniTask<string> DoJoinAsync(MessagingJoiningConfig connectionConfig, string localClientId)
localClientIdとなってますが、localは必要ですか？clientIdだとダメでしょうか？
あと、このclientIdはどこから来るのでしょうか？

2024-01-26 10:46 UTC, kiyohome commented on Runtime/RedisMessagingClient.cs
> +            var localClientId = Guid.NewGuid().ToString();
どうしてこのIDを生成してるんでしょうか？
サーバー側でクライアントを識別するID（今回だとsocketのid）だとダメでしょうか？

2024-01-26 10:46 UTC, kiyohome commented on WebScripts~/package.json
> +    "socket.io-client": "^4.7.1"
最新4.7.4ですね

2024-01-29 01:44 UTC, mahaweilu commented on MessagingServer~/compose.yaml
> +    messaging-redis:
以下が理由です。
開発中でよく[p2p.webrtcのsignalling-redis](https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/blob/ed7605736e8ee357797de754b26199fcae53a3b2/SignalingServer~/docker-compose.yaml#L5)も同時に起動するため、区分したほうがわかりやすいと考えています

2024-01-29 01:54 UTC, mahaweilu commented on MessagingServer~/compose.yaml
> +        image: redis:7.0.10-alpine
[利用ライブラリのバージョンアップ](https://github.com/orgs/extreal-dev/projects/1/views/1?pane=issue&itemId=45885839)のPBIでDockerイメージバージョンアップ関連を対応しています。

PRのスコープに応じてPR分けて対応したほうがやりやすかったのが理由です。

2024-01-29 02:09 UTC, mahaweilu commented on MessagingServer~/compose.yaml
> +        tty: true
ttyとinitが不要で削除します。exposeが必要です。

2024-01-29 02:46 UTC, mahaweilu commented on MessagingServer~/index.ts
> +const getGroupsInfo = (): { groupList: Map<string, string>, groupMembers: Map<string, string[]> } => {
グループリストを取得する関数とグループメンバーを取得する関数の2つに分割することを行い対応します。

2024-01-29 02:47 UTC, mahaweilu commented on MessagingServer~/index.ts
> +const log = (...logMessages: (string | object)[]) => {
logメソッド呼び出しもとでisLogiingを見るように修正します。

2024-01-29 02:50 UTC, mahaweilu commented on MessagingServer~/index.ts
> +    const maxCapacityStr = await this.client.get(`MaxCapacity#${groupName}`);
今回は単一のサーバインスタンスでやっているのでグローバル変数にmaxCapacity、clientIdとsocketIdのMapを管理すりように対応します。これによって性能が良くなります。

2024-01-29 02:50 UTC, mahaweilu commented on MessagingServer~/index.ts
> +    await this.client.set(clientId, socketId);
今回は単一のサーバインスタンスでやっているのでグローバル変数にmaxCapacity、clientIdとsocketIdのMapを管理すりように対応します。これによって性能が良くなります。

2024-01-29 02:51 UTC, mahaweilu commented on MessagingServer~/index.ts
> +  const groupsMap = io.of("/").adapter.rooms;
ありがとうございます。指摘通り対応します。

2024-01-29 04:13 UTC, mahaweilu commented on MessagingServer~/index.ts
> +      clientId: string,
>clientIdを指定せずにsocketIdをクライアントIDとしたらダメでしょうか？
良くないと思います。理由が以下です。
clientIdはクライアントアプリで保存する必要があります。socketIdがクライアントアプリで露出するとセキュリティ上良くないためサーバ側で管理した方が良いと思います。

2024-01-29 04:31 UTC, mahaweilu commented on MessagingServer~/index.ts
> +      maxCapacity: number,
>やりたいことは何でしょうか？

グループの上限人数を設定したいことです。

2024-01-29 04:50 UTC, mahaweilu commented on MessagingServer~/index.ts
> +  const handleDisconnect = async () => {
理由が以下です。

リファクタリングの観点から、`leave`と`disconnect`両方の同じ処理を抽出してメソッド化ししました。

2024-01-29 05:13 UTC, mahaweilu commented on MessagingServer~/index.ts
> +  let myGroupName = "";
取れます。

ただその場合は、クライアントアプリでユーザが入力したグループ名とsocket.idを管理することになります。クライアントアプリでsocket.idを露出しないほうがセキュリティ面に良いと思いますがどうでしょうか？

2024-01-29 05:19 UTC, mahaweilu commented on Runtime/NativeRedisMessagingClient.cs
> +                localClientId, connectionConfig.GroupName, connectionConfig.MaxCapacity
私もやはりMaxCapacityはサーバ側の状態なので、クライアントアプリで設定しないほうが自然な気がしてきています。ただ旧Holiday踏襲で「クライアントアプリで設定する」ことが要件だと思いましたが、違いますでしょうか？

2024-01-29 06:06 UTC, mahaweilu commented on Runtime/NativeRedisMessagingClient.cs
> +        protected override async UniTask<string> DoJoinAsync(MessagingJoiningConfig connectionConfig, string localClientId)
>ocalClientIdとなってますが、localは必要ですか？clientIdだとダメでしょうか？

localが必要ではなかったのでclientIdに修正します。（以前remoteClientIdとlocalClientIdのような命名がありましたが、今はclientIdに統一したほうが分かりやすいと思いました）

>このclientIdはどこから来るのでしょうか？

以下の指摘と同じ内容のためお手数ですが、そちらから参考お願いします。
https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1#discussion_r1467476818

2024-01-29 06:09 UTC, mahaweilu commented on Runtime/RedisMessagingClient.cs
> +            var localClientId = Guid.NewGuid().ToString();
こちらの回答と同じですが、クライアントアプリでsocketのidを露出するとセキュリティ上に良くないと考えています。
https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1#discussion_r1469056902

2024-01-29 06:10 UTC, mahaweilu commented on WebScripts~/package.json
> +    "socket.io-client": "^4.7.1"
[利用ライブラリのバージョンアップ](https://github.com/orgs/extreal-dev/projects/1/views/1?pane=issue&itemId=45885839)のPBIでバージョンアップ関連を対応しています。以下がPRで本PRのブランチから切っている形にしています。
・https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/2

PRのスコープに応じてPR分けて対応したほうがやりやすかったのが理由です。

2024-01-29 08:26 UTC, mahaweilu commented on MessagingServer~/index.ts
> +const getGroupsInfo = (): { groupList: Map<string, string>, groupMembers: Map<string, string[]> } => {
関数を2つに分割して対応しました。
[fb4cf58](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/fb4cf58af62ef6f05bf626ec31d35564c92f5154)

2024-01-29 08:27 UTC, mahaweilu commented on MessagingServer~/index.ts
> +  const groupsMap = io.of("/").adapter.rooms;
関連する命名を変えました。
[fb4cf58](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/fb4cf58af62ef6f05bf626ec31d35564c92f5154)

2024-01-29 08:53 UTC, mahaweilu commented on MessagingServer~/index.ts
> +    await this.client.set(clientId, socketId);
スティックセッション

2024-01-29 09:04 UTC, mahaweilu commented on MessagingServer~/index.ts
> +      clientId: string,
どういう場合

2024-01-29 09:08 UTC, mahaweilu commented on MessagingServer~/index.ts
> +      maxCapacity: number,
新規という観点

2024-01-29 09:20 UTC, mahaweilu commented on MessagingServer~/index.ts
> +  const handleDisconnect = async () => {
命名、handleLeve

2024-01-29 09:24 UTC, mahaweilu commented on MessagingServer~/index.ts
> +  let myGroupName = "";
サーバ側で管理しない

2024-01-30 12:41 UTC, mahaweilu commented on WebScripts~/package.json
> +    "socket.io-client": "^4.7.1"
対応しました。
[f07ac43](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/f07ac43674df0cd899a44ca55c0a638c596fe4ca)

2024-01-30 13:09 UTC, mahaweilu commented on MessagingServer~/index.ts
> +const log = (...logMessages: (string | object)[]) => {
p2pの時と同じように関数を渡す形で修正しました。
[711bab1](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/711bab14e7548c0e5a997498ed3353ea0a67863c)

2024-01-31 02:19 UTC, sus-yoshikane-t commented on MessagingServer~/index.ts
> +const getGroupsInfo = (): { groupList: Map<string, string>, groupMembers: Map<string, string[]> } => {
メモ：P2Pと同様にする

2024-01-31 02:25 UTC, sus-yoshikane-t commented on MessagingServer~/index.ts
> +      clientId: string,
メモ：SocketIDを使用する

2024-01-31 02:25 UTC, sus-yoshikane-t commented on MessagingServer~/index.ts
> +      maxCapacity: number,
メモ：サーバー側で設定する

2024-01-31 02:30 UTC, sus-yoshikane-t commented on MessagingServer~/index.ts
> +  let myGroupName = "";
メモ：P2Pと同様にする

2024-01-31 02:32 UTC, sus-yoshikane-t commented on Runtime/NativeRedisMessagingClient.cs
> +        protected override async UniTask<string> DoJoinAsync(MessagingJoiningConfig connectionConfig, string localClientId)
メモ：サーバー側で分かるのでclientIdは送らない

2024-01-31 12:49 UTC, mahaweilu commented on MessagingServer~/compose.yaml
> +        tty: true
3つ全部削除して対応しました。exposeについて、redisにmaxCapacityやclientIdを保存しなくしたため、要らなくなっています。
[78bf429](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/78bf429e7b32a57f8e6feb7184f1e914152262da)

2024-01-31 12:50 UTC, mahaweilu commented on MessagingServer~/index.ts
> +    const maxCapacityStr = await this.client.get(`MaxCapacity#${groupName}`);
redisにmaxCapacityやclientIdを保存しなくしたため、RedisClientクラスが要らなくなっています。以下に修正を反映しています。
[78bf429](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/78bf429e7b32a57f8e6feb7184f1e914152262da)

2024-01-31 12:51 UTC, mahaweilu commented on MessagingServer~/index.ts
> +    await this.client.set(clientId, socketId);
redisにmaxCapacityやclientIdを保存しなくしたため、RedisClientクラスが要らなくなっています。以下に修正を反映しています。
[78bf429](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/78bf429e7b32a57f8e6feb7184f1e914152262da)

2024-01-31 12:52 UTC, mahaweilu commented on MessagingServer~/index.ts
> +      clientId: string,
サーバ側でclientIdを指定せず対応しました。
[78bf429](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/78bf429e7b32a57f8e6feb7184f1e914152262da)

2024-02-01 00:16 UTC, mahaweilu commented on MessagingServer~/index.ts
> +const getGroupsInfo = (): { groupList: Map<string, string>, groupMembers: Map<string, string[]> } => {
"list groups"関連するとことをp2p.webrtcと同じような書き方に修正しました。
[7b4999a](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/7b4999a0f30c621f22afd51cf0c3dbc0c738947c)

2024-02-01 00:17 UTC, mahaweilu commented on MessagingServer~/index.ts
> +      maxCapacity: number,
サーバ側で流量制限として固定設定するように修正しました。
https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/78bf429e7b32a57f8e6feb7184f1e914152262da

2024-02-02 01:37 UTC, sus-yoshikane-t commented on MessagingServer~/index.ts
> +    const maxCapacityStr = await this.client.get(`MaxCapacity#${groupName}`);
追加で`compose.yaml`で`maxCapacity`を設定できるように修正しました。https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/b0566856f865b62b283e329d1c0d00d62770555a

2024-02-02 02:00 UTC, sus-yoshikane-t commented on MessagingServer~/index.ts
> +const getGroupsInfo = (): { groupList: Map<string, string>, groupMembers: Map<string, string[]> } => {
追加の変更として、GroupのIDを使用していなかったため削除しました。https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/59c1dc67d31a809883ff36d60668c63d3b0735be https://github.com/extreal-dev/Extreal.Integration.Messaging/pull/3/commits/64aec23aba948cea28f77a73c6e7bc647b707ae6

2024-02-02 02:24 UTC, sus-yoshikane-t commented on MessagingServer~/index.ts
> +  let myGroupName = "";
`socket.id`と`socket.rooms`を使用するように修正しました。https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/2376f537e4b1e50cae54edc5b28ab533df0f8880

補足：
`socket.rooms`には（デフォルトで入室する自分自身のみの）socket.idと同名のルームも含まれていますが、`socket.to().emit()`では[自分自身には送信が行われない](https://socket.io/docs/v4/server-api/#sockettoroom)ため、`socket.on("message")`とleaveで多少処理が変わっています。

2024-02-02 02:27 UTC, sus-yoshikane-t commented on Runtime/NativeRedisMessagingClient.cs
> +                localClientId, connectionConfig.GroupName, connectionConfig.MaxCapacity
修正しました。https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/9dd5e25377652b6b15dc71c7effa943c7c2e1a65

2024-02-02 02:27 UTC, sus-yoshikane-t commented on Runtime/NativeRedisMessagingClient.cs
> +        protected override async UniTask<string> DoJoinAsync(MessagingJoiningConfig connectionConfig, string localClientId)
修正しました。https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/9dd5e25377652b6b15dc71c7effa943c7c2e1a65

2024-02-02 02:28 UTC, sus-yoshikane-t commented on Runtime/RedisMessagingClient.cs
> +            var localClientId = Guid.NewGuid().ToString();
修正しました。https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/9dd5e25377652b6b15dc71c7effa943c7c2e1a65

2024-02-02 05:34 UTC, kiyohome requested changes

2024-02-02 05:34 UTC, kiyohome commented on MessagingServer~/index.ts
> +    // @ts-ignore See https://socket.io/docs/v4/rooms/#implementation-details
このコメントは必要ですか？

2024-02-02 07:30 UTC, kiyohome requested changes

2024-02-02 07:30 UTC, kiyohome commented on MessagingServer~/index.ts
> +            let connectedClientNum = 0;
もっとシンプルにできないでしょうか？
```
const clients = rooms().get(groupName);
const isCapacityOver = clients && clients.size >= maxCapacity;
if (isCapacityOver) {
    log(() => `Reject client: ${socket.id}`);
    callback("rejected");
    return;
}
```

2024-02-02 08:12 UTC, sus-yoshikane-t commented on MessagingServer~/index.ts
> +            let connectedClientNum = 0;
修正しました。https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/b1ddbc2c109953d47d9fdf2d9a0cf6ff7794c1a5

2024-02-02 08:13 UTC, sus-yoshikane-t commented on MessagingServer~/index.ts
> +    // @ts-ignore See https://socket.io/docs/v4/rooms/#implementation-details
こちらの環境で消して問題なかったため削除しました。https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/bd20e29625ea1c72e1d209a4bd4a897e020dd910

2024-02-02 08:37 UTC, kiyohome approved these changes

2024-02-02 08:54 UTC, sus-yoshikane-t commented on Runtime/Extreal.Integration.Messaging.Redis.asmdef
> +        "Extreal.SampleApp.Holiday.Analyzer",
削除しました。https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/pull/1/commits/2a1cdb6946abc8a2978751bcd139a8ffd3d67d1e

2024-02-02 08:54 UTC, merged